# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: stablecoin-indexer
description: Multi-token stablecoin indexer (USDC, USDT)

field_selection:
  transaction_fields:
    - hash

contracts:
  - name: ERC20
    events:
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"

chains:
  # - id: 130 # Unichain
  #   start_block: 0
  #   contracts:
  #     - name: ERC20
  #       address:
  #         - 0x078D782b760474a361dDA0AF3839290b0EF57AD6
  #         - 0x9151434b16b9763660705744891fA906F660EcC5
  - id: 1 # Mainnet
    start_block: 0
    contracts:
      - name: ERC20
        address:
          - 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
  # - id: 42161 # Arbitrum.
  #   start_block: 0
  #   contracts:
  #     - name: ERC20
  #       address: 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
