# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: usdc-stablecoin-indexer
description: Comprehensive USDC stablecoin indexer

field_selection:
  transaction_fields:
    - hash

contracts:
  - name: ERC20
    events:
      - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"

chains:
  - id: 130 # Unichain
    start_block: 0
    contracts:
      - name: ERC20
        address: 0x078D782b760474a361dDA0AF3839290b0EF57AD6
  - id: 42161 # Arbitrum
    start_block: 0
    contracts:
      - name: ERC20
        address: 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
